serve:
  proxy:
    port: 4455
  api:
    port: 4456

access_rules:
  matching_strategy: regexp
  repositories:
    - file:///etc/access-rules.json

log:
  level: debug


authenticators:
  cookie_session:
    enabled: true
    config:
      check_session_url: http://kratos:4433/sessions/whoami
      subject_from: identity.id
      extra_from: "@this"
      # forward_http_headers: 
      #   - Cookie 

authorizers:
  allow:
    enabled: true
#     config:
#       remote: http://authz_adapter:3001/check

    
mutators:
  header:
    enabled: true
    config:
      headers:
        x-user: "{{ print .Subject }}"
 
errors:
  fallback:
    - json
