apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper
  labels:
    app: oathkeeper
spec:
  replicas: 1

  selector:
    matchLabels:
      app: oathkeeper

  template:
    metadata:
      labels:
        app: oathkeeper

    spec:
      containers:
        - name: oathkeeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: ["oathkeeper", "serve", "-c", "/etc/config/oathkeeper.yml"]

          ports:
            - name: proxy
              containerPort: 4455
            - name: api
              containerPort: 4456

          volumeMounts:
            - name: rules
              mountPath: /etc/access-rules.json
              subPath: access-rules.json

            - name: config
              mountPath: /etc/config/oathkeeper.yml
              subPath: config.yml

      volumes:
        - name: rules
          configMap:
            name: oathkeeper-rules

        - name: config
          configMap:
            name: oathkeeper-config