apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oathkeeper
  template:
    metadata:
      labels:
        app: oathkeeper
    spec:
      containers:
        - name: oathkeeper
          image: oryd/oathkeeper:v0.40.6
          args: ["serve", "-c", "/etc/oathkeeper/config.yml"]
          ports:
            - containerPort: 4455
            - containerPort: 4456
          volumeMounts:
            - name: config
              mountPath: /etc/oathkeeper
            - name: rules
              mountPath: /etc/rules
      volumes:
        - name: config
          configMap:
            name: oathkeeper-config
        - name: rules
          configMap: 
            name: oathkeeper-rules